apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: my-iperf3
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-port
    port: 5201
    protocol: TCP
    targetPort: 5201
  - name: udp-port
    port: 5201
    protocol: UDP
    targetPort: 5201
  selector:
    app: iperf3

