apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: my-iperf3
  namespace: iperf3-server
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: udp-port
    port: 5201
    protocol: UDP
    targetPort: 5201
  selector:
    app: iperf3
    
