apiVersion: v1
kind: Namespace
metadata:
  name: iperf3-system
  labels: 
    app: iperf3-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server-deployment
  labels:
    app: iperf3-server
  namespace: iperf3-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      containers:
      - name: iperf3-server
        image: sofianinho/iperf3:3.6-ubuntu18.04  
        args: ["-s"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5201
